// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: internal/ipc/pb/ipc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version   int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Title     string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body      string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags      []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Namespace string                 `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Entry) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Entry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body      string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Tags      []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Namespace string   `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *NoteAdd) Reset() {
	*x = NoteAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteAdd) ProtoMessage() {}

func (x *NoteAdd) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteAdd.ProtoReflect.Descriptor instead.
func (*NoteAdd) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *NoteAdd) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteAdd) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NoteAdd) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NoteAdd) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteEdit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IfVersion int64    `protobuf:"varint,2,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"`
	Title     string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body      string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags      []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Namespace string   `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *NoteEdit) Reset() {
	*x = NoteEdit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteEdit) ProtoMessage() {}

func (x *NoteEdit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteEdit.ProtoReflect.Descriptor instead.
func (*NoteEdit) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *NoteEdit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteEdit) GetIfVersion() int64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

func (x *NoteEdit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteEdit) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NoteEdit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NoteEdit) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *NoteDelete) Reset() {
	*x = NoteDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteDelete) ProtoMessage() {}

func (x *NoteDelete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteDelete.ProtoReflect.Descriptor instead.
func (*NoteDelete) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *NoteDelete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteDelete) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteShow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *NoteShow) Reset() {
	*x = NoteShow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteShow) ProtoMessage() {}

func (x *NoteShow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteShow.ProtoReflect.Descriptor instead.
func (*NoteShow) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *NoteShow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteShow) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TagsAny   []string               `protobuf:"bytes,2,rep,name=tags_any,json=tagsAny,proto3" json:"tags_any,omitempty"`
	TagsAll   []string               `protobuf:"bytes,3,rep,name=tags_all,json=tagsAll,proto3" json:"tags_all,omitempty"`
	Since     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Until     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListFilter) GetTagsAny() []string {
	if x != nil {
		return x.TagsAny
	}
	return nil
}

func (x *ListFilter) GetTagsAll() []string {
	if x != nil {
		return x.TagsAll
	}
	return nil
}

func (x *ListFilter) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListFilter) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type SearchFTS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string      `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Filter *ListFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SearchFTS) Reset() {
	*x = SearchFTS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFTS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFTS) ProtoMessage() {}

func (x *SearchFTS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFTS.ProtoReflect.Descriptor instead.
func (*SearchFTS) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *SearchFTS) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFTS) GetFilter() *ListFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchRegex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern string      `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Filter  *ListFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SearchRegex) Reset() {
	*x = SearchRegex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRegex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRegex) ProtoMessage() {}

func (x *SearchRegex) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRegex.ProtoReflect.Descriptor instead.
func (*SearchRegex) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRegex) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchRegex) GetFilter() *ListFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Cmd:
	//
	//	*Request_NoteAdd
	//	*Request_NoteEdit
	//	*Request_NoteDelete
	//	*Request_NoteShow
	//	*Request_NoteList
	//	*Request_NoteSearchFts
	//	*Request_NoteSearchRegex
	Cmd isRequest_Cmd `protobuf_oneof:"cmd"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{8}
}

func (m *Request) GetCmd() isRequest_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (x *Request) GetNoteAdd() *NoteAdd {
	if x, ok := x.GetCmd().(*Request_NoteAdd); ok {
		return x.NoteAdd
	}
	return nil
}

func (x *Request) GetNoteEdit() *NoteEdit {
	if x, ok := x.GetCmd().(*Request_NoteEdit); ok {
		return x.NoteEdit
	}
	return nil
}

func (x *Request) GetNoteDelete() *NoteDelete {
	if x, ok := x.GetCmd().(*Request_NoteDelete); ok {
		return x.NoteDelete
	}
	return nil
}

func (x *Request) GetNoteShow() *NoteShow {
	if x, ok := x.GetCmd().(*Request_NoteShow); ok {
		return x.NoteShow
	}
	return nil
}

func (x *Request) GetNoteList() *ListFilter {
	if x, ok := x.GetCmd().(*Request_NoteList); ok {
		return x.NoteList
	}
	return nil
}

func (x *Request) GetNoteSearchFts() *SearchFTS {
	if x, ok := x.GetCmd().(*Request_NoteSearchFts); ok {
		return x.NoteSearchFts
	}
	return nil
}

func (x *Request) GetNoteSearchRegex() *SearchRegex {
	if x, ok := x.GetCmd().(*Request_NoteSearchRegex); ok {
		return x.NoteSearchRegex
	}
	return nil
}

type isRequest_Cmd interface {
	isRequest_Cmd()
}

type Request_NoteAdd struct {
	NoteAdd *NoteAdd `protobuf:"bytes,1,opt,name=note_add,json=noteAdd,proto3,oneof"`
}

type Request_NoteEdit struct {
	NoteEdit *NoteEdit `protobuf:"bytes,2,opt,name=note_edit,json=noteEdit,proto3,oneof"`
}

type Request_NoteDelete struct {
	NoteDelete *NoteDelete `protobuf:"bytes,3,opt,name=note_delete,json=noteDelete,proto3,oneof"`
}

type Request_NoteShow struct {
	NoteShow *NoteShow `protobuf:"bytes,4,opt,name=note_show,json=noteShow,proto3,oneof"`
}

type Request_NoteList struct {
	NoteList *ListFilter `protobuf:"bytes,5,opt,name=note_list,json=noteList,proto3,oneof"`
}

type Request_NoteSearchFts struct {
	NoteSearchFts *SearchFTS `protobuf:"bytes,6,opt,name=note_search_fts,json=noteSearchFts,proto3,oneof"`
}

type Request_NoteSearchRegex struct {
	NoteSearchRegex *SearchRegex `protobuf:"bytes,7,opt,name=note_search_regex,json=noteSearchRegex,proto3,oneof"`
}

func (*Request_NoteAdd) isRequest_Cmd() {}

func (*Request_NoteEdit) isRequest_Cmd() {}

func (*Request_NoteDelete) isRequest_Cmd() {}

func (*Request_NoteShow) isRequest_Cmd() {}

func (*Request_NoteList) isRequest_Cmd() {}

func (*Request_NoteSearchFts) isRequest_Cmd() {}

func (*Request_NoteSearchRegex) isRequest_Cmd() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg     string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Entry   *Entry   `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	Entries []*Entry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ipc_pb_ipc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *Response) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_internal_ipc_pb_ipc_proto protoreflect.FileDescriptor

var file_internal_ipc_pb_ipc_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x70, 0x63, 0x2f, 0x70,
	0x62, 0x2f, 0x69, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x70, 0x63,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x83, 0x02, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x65, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x65, 0x41,
	0x64, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x95,
	0x01, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x45, 0x64, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x66, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x69, 0x66, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x22, 0x38, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xc4, 0x01, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67,
	0x73, 0x5f, 0x61, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67,
	0x73, 0x41, 0x6e, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x73, 0x5f, 0x61, 0x6c, 0x6c,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x73, 0x41, 0x6c, 0x6c, 0x12,
	0x30, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x69, 0x6e, 0x63,
	0x65, 0x12, 0x30, 0x0a, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x75, 0x6e,
	0x74, 0x69, 0x6c, 0x22, 0x4a, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x54, 0x53,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x50, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x67, 0x65, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x22, 0xf5, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x08, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x48, 0x00, 0x52,
	0x07, 0x6e, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x65,
	0x5f, 0x65, 0x64, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x70,
	0x63, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x45, 0x64, 0x69, 0x74, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f,
	0x74, 0x65, 0x45, 0x64, 0x69, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x70,
	0x63, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0a,
	0x6e, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x6e, 0x6f,
	0x74, 0x65, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x69, 0x70, 0x63, 0x2e, 0x4e, 0x6f, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x48, 0x00, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x2e, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x65,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x70,
	0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x65,
	0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x66, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x54,
	0x53, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46,
	0x74, 0x73, 0x12, 0x3e, 0x0a, 0x11, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x69, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x67, 0x65, 0x78, 0x48,
	0x00, 0x52, 0x0f, 0x6e, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x67,
	0x65, 0x78, 0x42, 0x05, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x74, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x69, 0x70, 0x63,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42,
	0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69,
	0x74, 0x68, 0x72, 0x65, 0x6c, 0x2f, 0x67, 0x69, 0x6e, 0x6b, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ipc_pb_ipc_proto_rawDescOnce sync.Once
	file_internal_ipc_pb_ipc_proto_rawDescData = file_internal_ipc_pb_ipc_proto_rawDesc
)

func file_internal_ipc_pb_ipc_proto_rawDescGZIP() []byte {
	file_internal_ipc_pb_ipc_proto_rawDescOnce.Do(func() {
		file_internal_ipc_pb_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ipc_pb_ipc_proto_rawDescData)
	})
	return file_internal_ipc_pb_ipc_proto_rawDescData
}

var file_internal_ipc_pb_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_ipc_pb_ipc_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: ipc.Entry
	(*NoteAdd)(nil),               // 1: ipc.NoteAdd
	(*NoteEdit)(nil),              // 2: ipc.NoteEdit
	(*NoteDelete)(nil),            // 3: ipc.NoteDelete
	(*NoteShow)(nil),              // 4: ipc.NoteShow
	(*ListFilter)(nil),            // 5: ipc.ListFilter
	(*SearchFTS)(nil),             // 6: ipc.SearchFTS
	(*SearchRegex)(nil),           // 7: ipc.SearchRegex
	(*Request)(nil),               // 8: ipc.Request
	(*Response)(nil),              // 9: ipc.Response
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_internal_ipc_pb_ipc_proto_depIdxs = []int32{
	10, // 0: ipc.Entry.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: ipc.Entry.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: ipc.ListFilter.since:type_name -> google.protobuf.Timestamp
	10, // 3: ipc.ListFilter.until:type_name -> google.protobuf.Timestamp
	5,  // 4: ipc.SearchFTS.filter:type_name -> ipc.ListFilter
	5,  // 5: ipc.SearchRegex.filter:type_name -> ipc.ListFilter
	1,  // 6: ipc.Request.note_add:type_name -> ipc.NoteAdd
	2,  // 7: ipc.Request.note_edit:type_name -> ipc.NoteEdit
	3,  // 8: ipc.Request.note_delete:type_name -> ipc.NoteDelete
	4,  // 9: ipc.Request.note_show:type_name -> ipc.NoteShow
	5,  // 10: ipc.Request.note_list:type_name -> ipc.ListFilter
	6,  // 11: ipc.Request.note_search_fts:type_name -> ipc.SearchFTS
	7,  // 12: ipc.Request.note_search_regex:type_name -> ipc.SearchRegex
	0,  // 13: ipc.Response.entry:type_name -> ipc.Entry
	0,  // 14: ipc.Response.entries:type_name -> ipc.Entry
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_ipc_pb_ipc_proto_init() }
func file_internal_ipc_pb_ipc_proto_init() {
	if File_internal_ipc_pb_ipc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ipc_pb_ipc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NoteAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NoteEdit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NoteDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*NoteShow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SearchFTS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SearchRegex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ipc_pb_ipc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_ipc_pb_ipc_proto_msgTypes[8].OneofWrappers = []any{
		(*Request_NoteAdd)(nil),
		(*Request_NoteEdit)(nil),
		(*Request_NoteDelete)(nil),
		(*Request_NoteShow)(nil),
		(*Request_NoteList)(nil),
		(*Request_NoteSearchFts)(nil),
		(*Request_NoteSearchRegex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ipc_pb_ipc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ipc_pb_ipc_proto_goTypes,
		DependencyIndexes: file_internal_ipc_pb_ipc_proto_depIdxs,
		MessageInfos:      file_internal_ipc_pb_ipc_proto_msgTypes,
	}.Build()
	File_internal_ipc_pb_ipc_proto = out.File
	file_internal_ipc_pb_ipc_proto_rawDesc = nil
	file_internal_ipc_pb_ipc_proto_goTypes = nil
	file_internal_ipc_pb_ipc_proto_depIdxs = nil
}
