// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/ipc/pb/ipc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Namespace     string                 `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Entry) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Entry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteAdd) Reset() {
	*x = NoteAdd{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteAdd) ProtoMessage() {}

func (x *NoteAdd) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteAdd.ProtoReflect.Descriptor instead.
func (*NoteAdd) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *NoteAdd) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteAdd) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NoteAdd) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NoteAdd) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IfVersion     int64                  `protobuf:"varint,2,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteEdit) Reset() {
	*x = NoteEdit{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteEdit) ProtoMessage() {}

func (x *NoteEdit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteEdit.ProtoReflect.Descriptor instead.
func (*NoteEdit) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *NoteEdit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteEdit) GetIfVersion() int64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

func (x *NoteEdit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteEdit) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NoteEdit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NoteEdit) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteDelete) Reset() {
	*x = NoteDelete{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteDelete) ProtoMessage() {}

func (x *NoteDelete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteDelete.ProtoReflect.Descriptor instead.
func (*NoteDelete) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *NoteDelete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteDelete) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NoteShow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteShow) Reset() {
	*x = NoteShow{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteShow) ProtoMessage() {}

func (x *NoteShow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteShow.ProtoReflect.Descriptor instead.
func (*NoteShow) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *NoteShow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteShow) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TagsAny       []string               `protobuf:"bytes,2,rep,name=tags_any,json=tagsAny,proto3" json:"tags_any,omitempty"`
	TagsAll       []string               `protobuf:"bytes,3,rep,name=tags_all,json=tagsAll,proto3" json:"tags_all,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListFilter) GetTagsAny() []string {
	if x != nil {
		return x.TagsAny
	}
	return nil
}

func (x *ListFilter) GetTagsAll() []string {
	if x != nil {
		return x.TagsAll
	}
	return nil
}

func (x *ListFilter) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListFilter) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type SearchFTS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Filter        *ListFilter            `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFTS) Reset() {
	*x = SearchFTS{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFTS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFTS) ProtoMessage() {}

func (x *SearchFTS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFTS.ProtoReflect.Descriptor instead.
func (*SearchFTS) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *SearchFTS) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFTS) GetFilter() *ListFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchRegex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Filter        *ListFilter            `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRegex) Reset() {
	*x = SearchRegex{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRegex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRegex) ProtoMessage() {}

func (x *SearchRegex) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRegex.ProtoReflect.Descriptor instead.
func (*SearchRegex) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRegex) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchRegex) GetFilter() *ListFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Request_NoteAdd
	//	*Request_NoteEdit
	//	*Request_NoteDelete
	//	*Request_NoteShow
	//	*Request_NoteList
	//	*Request_NoteSearchFts
	//	*Request_NoteSearchRegex
	//	*Request_SyncRun
	//	*Request_QueueList
	//	*Request_NamespaceList
	Cmd           isRequest_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *Request) GetCmd() isRequest_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Request) GetNoteAdd() *NoteAdd {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteAdd); ok {
			return x.NoteAdd
		}
	}
	return nil
}

func (x *Request) GetNoteEdit() *NoteEdit {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteEdit); ok {
			return x.NoteEdit
		}
	}
	return nil
}

func (x *Request) GetNoteDelete() *NoteDelete {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteDelete); ok {
			return x.NoteDelete
		}
	}
	return nil
}

func (x *Request) GetNoteShow() *NoteShow {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteShow); ok {
			return x.NoteShow
		}
	}
	return nil
}

func (x *Request) GetNoteList() *ListFilter {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteList); ok {
			return x.NoteList
		}
	}
	return nil
}

func (x *Request) GetNoteSearchFts() *SearchFTS {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteSearchFts); ok {
			return x.NoteSearchFts
		}
	}
	return nil
}

func (x *Request) GetNoteSearchRegex() *SearchRegex {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NoteSearchRegex); ok {
			return x.NoteSearchRegex
		}
	}
	return nil
}

func (x *Request) GetSyncRun() *SyncRun {
	if x != nil {
		if x, ok := x.Cmd.(*Request_SyncRun); ok {
			return x.SyncRun
		}
	}
	return nil
}

func (x *Request) GetQueueList() *QueueRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_QueueList); ok {
			return x.QueueList
		}
	}
	return nil
}

func (x *Request) GetNamespaceList() *NamespaceList {
	if x != nil {
		if x, ok := x.Cmd.(*Request_NamespaceList); ok {
			return x.NamespaceList
		}
	}
	return nil
}

type isRequest_Cmd interface {
	isRequest_Cmd()
}

type Request_NoteAdd struct {
	NoteAdd *NoteAdd `protobuf:"bytes,1,opt,name=note_add,json=noteAdd,proto3,oneof"`
}

type Request_NoteEdit struct {
	NoteEdit *NoteEdit `protobuf:"bytes,2,opt,name=note_edit,json=noteEdit,proto3,oneof"`
}

type Request_NoteDelete struct {
	NoteDelete *NoteDelete `protobuf:"bytes,3,opt,name=note_delete,json=noteDelete,proto3,oneof"`
}

type Request_NoteShow struct {
	NoteShow *NoteShow `protobuf:"bytes,4,opt,name=note_show,json=noteShow,proto3,oneof"`
}

type Request_NoteList struct {
	NoteList *ListFilter `protobuf:"bytes,5,opt,name=note_list,json=noteList,proto3,oneof"`
}

type Request_NoteSearchFts struct {
	NoteSearchFts *SearchFTS `protobuf:"bytes,6,opt,name=note_search_fts,json=noteSearchFts,proto3,oneof"`
}

type Request_NoteSearchRegex struct {
	NoteSearchRegex *SearchRegex `protobuf:"bytes,7,opt,name=note_search_regex,json=noteSearchRegex,proto3,oneof"`
}

type Request_SyncRun struct {
	SyncRun *SyncRun `protobuf:"bytes,8,opt,name=sync_run,json=syncRun,proto3,oneof"`
}

type Request_QueueList struct {
	QueueList *QueueRequest `protobuf:"bytes,9,opt,name=queue_list,json=queueList,proto3,oneof"`
}

type Request_NamespaceList struct {
	NamespaceList *NamespaceList `protobuf:"bytes,10,opt,name=namespace_list,json=namespaceList,proto3,oneof"`
}

func (*Request_NoteAdd) isRequest_Cmd() {}

func (*Request_NoteEdit) isRequest_Cmd() {}

func (*Request_NoteDelete) isRequest_Cmd() {}

func (*Request_NoteShow) isRequest_Cmd() {}

func (*Request_NoteList) isRequest_Cmd() {}

func (*Request_NoteSearchFts) isRequest_Cmd() {}

func (*Request_NoteSearchRegex) isRequest_Cmd() {}

func (*Request_SyncRun) isRequest_Cmd() {}

func (*Request_QueueList) isRequest_Cmd() {}

func (*Request_NamespaceList) isRequest_Cmd() {}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	Queue         []*QueueRemote         `protobuf:"bytes,5,rep,name=queue,proto3" json:"queue,omitempty"`
	Namespaces    []string               `protobuf:"bytes,6,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *Response) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Response) GetQueue() []*QueueRemote {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *Response) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type RepEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,4,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepEvent) Reset() {
	*x = RepEvent{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepEvent) ProtoMessage() {}

func (x *RepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepEvent.ProtoReflect.Descriptor instead.
func (*RepEvent) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{10}
}

func (x *RepEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RepEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RepEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RepEvent) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type PushBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RepEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatch) Reset() {
	*x = PushBatch{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatch) ProtoMessage() {}

func (x *PushBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatch.ProtoReflect.Descriptor instead.
func (*PushBatch) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{11}
}

func (x *PushBatch) GetEvents() []*RepEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ItemStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStatus) Reset() {
	*x = ItemStatus{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatus) ProtoMessage() {}

func (x *ItemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatus.ProtoReflect.Descriptor instead.
func (*ItemStatus) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{12}
}

func (x *ItemStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ItemStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{13}
}

func (x *Cursor) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.After
	}
	return nil
}

type PushResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStatus          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Next          *Cursor                `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResult) Reset() {
	*x = PushResult{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResult) ProtoMessage() {}

func (x *PushResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResult.ProtoReflect.Descriptor instead.
func (*PushResult) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{14}
}

func (x *PushResult) GetItems() []*ItemStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PushResult) GetNext() *Cursor {
	if x != nil {
		return x.Next
	}
	return nil
}

type PullResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RepEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Next          *Cursor                `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResult) Reset() {
	*x = PullResult{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResult) ProtoMessage() {}

func (x *PullResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResult.ProtoReflect.Descriptor instead.
func (*PullResult) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{15}
}

func (x *PullResult) GetEvents() []*RepEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PullResult) GetNext() *Cursor {
	if x != nil {
		return x.Next
	}
	return nil
}

type SyncRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRun) Reset() {
	*x = SyncRun{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRun) ProtoMessage() {}

func (x *SyncRun) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRun.ProtoReflect.Descriptor instead.
func (*SyncRun) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{16}
}

type NamespaceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceList) Reset() {
	*x = NamespaceList{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceList) ProtoMessage() {}

func (x *NamespaceList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceList.ProtoReflect.Descriptor instead.
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{17}
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Remote        string                 `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{18}
}

func (x *QueueRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueueRequest) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

type QueueEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueEvent) Reset() {
	*x = QueueEvent{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEvent) ProtoMessage() {}

func (x *QueueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEvent.ProtoReflect.Descriptor instead.
func (*QueueEvent) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{19}
}

func (x *QueueEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QueueEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueueEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueueRemote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Pending       int64                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Events        []*QueueEvent          `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRemote) Reset() {
	*x = QueueRemote{}
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRemote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemote) ProtoMessage() {}

func (x *QueueRemote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ipc_pb_ipc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemote.ProtoReflect.Descriptor instead.
func (*QueueRemote) Descriptor() ([]byte, []int) {
	return file_internal_ipc_pb_ipc_proto_rawDescGZIP(), []int{20}
}

func (x *QueueRemote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueRemote) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QueueRemote) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueRemote) GetEvents() []*QueueEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_internal_ipc_pb_ipc_proto protoreflect.FileDescriptor

const file_internal_ipc_pb_ipc_proto_rawDesc = "" +
	"\n" +
	"\x19internal/ipc/pb/ipc.proto\x12\x03ipc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tnamespace\x18\b \x01(\tR\tnamespace\"e\n" +
	"\aNoteAdd\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"\x95\x01\n" +
	"\bNoteEdit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"if_version\x18\x02 \x01(\x03R\tifVersion\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\":\n" +
	"\n" +
	"NoteDelete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"8\n" +
	"\bNoteShow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xc4\x01\n" +
	"\n" +
	"ListFilter\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\btags_any\x18\x02 \x03(\tR\atagsAny\x12\x19\n" +
	"\btags_all\x18\x03 \x03(\tR\atagsAll\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"J\n" +
	"\tSearchFTS\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12'\n" +
	"\x06filter\x18\x02 \x01(\v2\x0f.ipc.ListFilterR\x06filter\"P\n" +
	"\vSearchRegex\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12'\n" +
	"\x06filter\x18\x02 \x01(\v2\x0f.ipc.ListFilterR\x06filter\"\x91\x04\n" +
	"\aRequest\x12)\n" +
	"\bnote_add\x18\x01 \x01(\v2\f.ipc.NoteAddH\x00R\anoteAdd\x12,\n" +
	"\tnote_edit\x18\x02 \x01(\v2\r.ipc.NoteEditH\x00R\bnoteEdit\x122\n" +
	"\vnote_delete\x18\x03 \x01(\v2\x0f.ipc.NoteDeleteH\x00R\n" +
	"noteDelete\x12,\n" +
	"\tnote_show\x18\x04 \x01(\v2\r.ipc.NoteShowH\x00R\bnoteShow\x12.\n" +
	"\tnote_list\x18\x05 \x01(\v2\x0f.ipc.ListFilterH\x00R\bnoteList\x128\n" +
	"\x0fnote_search_fts\x18\x06 \x01(\v2\x0e.ipc.SearchFTSH\x00R\rnoteSearchFts\x12>\n" +
	"\x11note_search_regex\x18\a \x01(\v2\x10.ipc.SearchRegexH\x00R\x0fnoteSearchRegex\x12)\n" +
	"\bsync_run\x18\b \x01(\v2\f.ipc.SyncRunH\x00R\asyncRun\x122\n" +
	"\n" +
	"queue_list\x18\t \x01(\v2\x11.ipc.QueueRequestH\x00R\tqueueList\x12;\n" +
	"\x0enamespace_list\x18\n" +
	" \x01(\v2\x12.ipc.NamespaceListH\x00R\rnamespaceListB\x05\n" +
	"\x03cmd\"\xbc\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12 \n" +
	"\x05entry\x18\x03 \x01(\v2\n" +
	".ipc.EntryR\x05entry\x12$\n" +
	"\aentries\x18\x04 \x03(\v2\n" +
	".ipc.EntryR\aentries\x12&\n" +
	"\x05queue\x18\x05 \x03(\v2\x10.ipc.QueueRemoteR\x05queue\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x06 \x03(\tR\n" +
	"namespaces\"\x80\x01\n" +
	"\bRepEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12 \n" +
	"\x05entry\x18\x04 \x01(\v2\n" +
	".ipc.EntryR\x05entry\"2\n" +
	"\tPushBatch\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.ipc.RepEventR\x06events\">\n" +
	"\n" +
	"ItemStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\":\n" +
	"\x06Cursor\x120\n" +
	"\x05after\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05after\"T\n" +
	"\n" +
	"PushResult\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.ipc.ItemStatusR\x05items\x12\x1f\n" +
	"\x04next\x18\x02 \x01(\v2\v.ipc.CursorR\x04next\"T\n" +
	"\n" +
	"PullResult\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.ipc.RepEventR\x06events\x12\x1f\n" +
	"\x04next\x18\x02 \x01(\v2\v.ipc.CursorR\x04next\"\t\n" +
	"\aSyncRun\"\x0f\n" +
	"\rNamespaceList\"<\n" +
	"\fQueueRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06remote\x18\x02 \x01(\tR\x06remote\"`\n" +
	"\n" +
	"QueueEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"v\n" +
	"\vQueueRemote\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\apending\x18\x03 \x01(\x03R\apending\x12'\n" +
	"\x06events\x18\x04 \x03(\v2\x0f.ipc.QueueEventR\x06eventsB+Z)github.com/mithrel/ginkgo/internal/ipc/pbb\x06proto3"

var (
	file_internal_ipc_pb_ipc_proto_rawDescOnce sync.Once
	file_internal_ipc_pb_ipc_proto_rawDescData []byte
)

func file_internal_ipc_pb_ipc_proto_rawDescGZIP() []byte {
	file_internal_ipc_pb_ipc_proto_rawDescOnce.Do(func() {
		file_internal_ipc_pb_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ipc_pb_ipc_proto_rawDesc), len(file_internal_ipc_pb_ipc_proto_rawDesc)))
	})
	return file_internal_ipc_pb_ipc_proto_rawDescData
}

var file_internal_ipc_pb_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_ipc_pb_ipc_proto_goTypes = []any{
	(*Entry)(nil),                 // 0: ipc.Entry
	(*NoteAdd)(nil),               // 1: ipc.NoteAdd
	(*NoteEdit)(nil),              // 2: ipc.NoteEdit
	(*NoteDelete)(nil),            // 3: ipc.NoteDelete
	(*NoteShow)(nil),              // 4: ipc.NoteShow
	(*ListFilter)(nil),            // 5: ipc.ListFilter
	(*SearchFTS)(nil),             // 6: ipc.SearchFTS
	(*SearchRegex)(nil),           // 7: ipc.SearchRegex
	(*Request)(nil),               // 8: ipc.Request
	(*Response)(nil),              // 9: ipc.Response
	(*RepEvent)(nil),              // 10: ipc.RepEvent
	(*PushBatch)(nil),             // 11: ipc.PushBatch
	(*ItemStatus)(nil),            // 12: ipc.ItemStatus
	(*Cursor)(nil),                // 13: ipc.Cursor
	(*PushResult)(nil),            // 14: ipc.PushResult
	(*PullResult)(nil),            // 15: ipc.PullResult
	(*SyncRun)(nil),               // 16: ipc.SyncRun
	(*NamespaceList)(nil),         // 17: ipc.NamespaceList
	(*QueueRequest)(nil),          // 18: ipc.QueueRequest
	(*QueueEvent)(nil),            // 19: ipc.QueueEvent
	(*QueueRemote)(nil),           // 20: ipc.QueueRemote
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_internal_ipc_pb_ipc_proto_depIdxs = []int32{
	21, // 0: ipc.Entry.created_at:type_name -> google.protobuf.Timestamp
	21, // 1: ipc.Entry.updated_at:type_name -> google.protobuf.Timestamp
	21, // 2: ipc.ListFilter.since:type_name -> google.protobuf.Timestamp
	21, // 3: ipc.ListFilter.until:type_name -> google.protobuf.Timestamp
	5,  // 4: ipc.SearchFTS.filter:type_name -> ipc.ListFilter
	5,  // 5: ipc.SearchRegex.filter:type_name -> ipc.ListFilter
	1,  // 6: ipc.Request.note_add:type_name -> ipc.NoteAdd
	2,  // 7: ipc.Request.note_edit:type_name -> ipc.NoteEdit
	3,  // 8: ipc.Request.note_delete:type_name -> ipc.NoteDelete
	4,  // 9: ipc.Request.note_show:type_name -> ipc.NoteShow
	5,  // 10: ipc.Request.note_list:type_name -> ipc.ListFilter
	6,  // 11: ipc.Request.note_search_fts:type_name -> ipc.SearchFTS
	7,  // 12: ipc.Request.note_search_regex:type_name -> ipc.SearchRegex
	16, // 13: ipc.Request.sync_run:type_name -> ipc.SyncRun
	18, // 14: ipc.Request.queue_list:type_name -> ipc.QueueRequest
	17, // 15: ipc.Request.namespace_list:type_name -> ipc.NamespaceList
	0,  // 16: ipc.Response.entry:type_name -> ipc.Entry
	0,  // 17: ipc.Response.entries:type_name -> ipc.Entry
	20, // 18: ipc.Response.queue:type_name -> ipc.QueueRemote
	21, // 19: ipc.RepEvent.time:type_name -> google.protobuf.Timestamp
	0,  // 20: ipc.RepEvent.entry:type_name -> ipc.Entry
	10, // 21: ipc.PushBatch.events:type_name -> ipc.RepEvent
	21, // 22: ipc.Cursor.after:type_name -> google.protobuf.Timestamp
	12, // 23: ipc.PushResult.items:type_name -> ipc.ItemStatus
	13, // 24: ipc.PushResult.next:type_name -> ipc.Cursor
	10, // 25: ipc.PullResult.events:type_name -> ipc.RepEvent
	13, // 26: ipc.PullResult.next:type_name -> ipc.Cursor
	21, // 27: ipc.QueueEvent.time:type_name -> google.protobuf.Timestamp
	19, // 28: ipc.QueueRemote.events:type_name -> ipc.QueueEvent
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_internal_ipc_pb_ipc_proto_init() }
func file_internal_ipc_pb_ipc_proto_init() {
	if File_internal_ipc_pb_ipc_proto != nil {
		return
	}
	file_internal_ipc_pb_ipc_proto_msgTypes[8].OneofWrappers = []any{
		(*Request_NoteAdd)(nil),
		(*Request_NoteEdit)(nil),
		(*Request_NoteDelete)(nil),
		(*Request_NoteShow)(nil),
		(*Request_NoteList)(nil),
		(*Request_NoteSearchFts)(nil),
		(*Request_NoteSearchRegex)(nil),
		(*Request_SyncRun)(nil),
		(*Request_QueueList)(nil),
		(*Request_NamespaceList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ipc_pb_ipc_proto_rawDesc), len(file_internal_ipc_pb_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ipc_pb_ipc_proto_goTypes,
		DependencyIndexes: file_internal_ipc_pb_ipc_proto_depIdxs,
		MessageInfos:      file_internal_ipc_pb_ipc_proto_msgTypes,
	}.Build()
	File_internal_ipc_pb_ipc_proto = out.File
	file_internal_ipc_pb_ipc_proto_goTypes = nil
	file_internal_ipc_pb_ipc_proto_depIdxs = nil
}
